export default function Definition() {
	return (
	  <>
		<div className="flex flex-col  gap-1 py-2 px-4">
		  <h1 className="text-2xl  py-2 font-black"> 💻 Developer Ecosystem </h1>
		  <h2 className="text-xl font-bold pb-2">
			Definition of impact
		  </h2>
		  <p>
		  Developer Ecosystem refers to the collective of actors, conditions, tooling and resources that enables people to build on the OP Chains. 
			<br />
			Impact to the Developer Ecosystem is generated by contributions that create the conditions for a thriving community where individuals and teams want to build products that people want to use. 
		  </p>
		  <span className="gap-2 py-3 px-1 rounded-md text-base font-medium text-zinc-300 bg-zinc-800 hover:text-white transition-colors">
		  🔴  There have been {" "}
			<a
			  href="https://dune.com/oplabspbc/developer-metrics-sploring"
			  className="text-white/50 underline"
			  target="_blank"
			  rel="noopener noreferrer"
			>
			  555 active deployers {" "}
			</a> 
			of production code to OP Mainnet in the last 28 days (Oct. 18th). We need moar!
		  </span>
		</div>
	  </>
	);
  }
  