export default function MetricsTable() {
  return (
	<>
	  <CollapsibleII
		TableData={[
		  {
			metric: "Content impressions",
			strength: "Low",
			description:
			  "Measures: Number of impressions this piece of content has had. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric.",
			keyword: "Familiarity",
		  },
		  {
			metric: "Number of Github stars",
			strength: "Low",
			description:
			  "Measures: Number of stars a Github repo has received. Why this level? There is no clear way to know if starring a project can be equated to any value being derived from it. ",
			keyword: "Familiarity",
		  },
		  {
			metric: "Number of event attendees",
			strength: "Low",
			description:
			  "Measures: Number of people who attended an event. Why this level? Depending on the type and content in the event, its value to the Optimism Ecosystem may be low or high based on how fruitful it is to engage people with Optimism. ",
			keyword: "Understanding",
		  },
		  {
			metric: "Number of content material created on the OP Stack",
			strength: "Low",
			description:
			  "Measures: Content created on the OP Stack. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric.",
			keyword: "Familiarity",
		  },
		  {
			metric: "Level of engagement with OP Stack content",
			strength: "Low",
			description:
			  "Measures: Engagement a piece of content has had. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric.",
			keyword: "Understanding",
		  },
		  {
			metric: "Runtime gas costs reduction",
			strength: "High",
			description:
			  "Measures: Reduction in runtime generated by a contribution. Why this level? Increase in the efficiency and performance of the OP Stack makes its operation more affordable.",
			keyword: "Gas Fees",
		  },
		  {
			metric: "Response time for RPC calls",
			strength: "High",
			description:
			  "Measures:Time to get a response to an RPC call. Why this level? A low response time to RPC calls makes developing and operating in the Optimism Ecosystem reliable.",
			keyword: "Reliability",
		  },
		  {
			metric: "Total OP Chains RPC served",
			strength: "High",
			description:
			  " Measures: Dependencies on OP Chains on a particular RPC. Why this level? An increase in the provision of service to OP Chains enables the creation of redundancy in case of malfunctions. ",
			keyword: "Reliability",
		  },
		  {
			metric: "Performance Improvement",
			strength: "High",
			description:
			  " Measures: Improvement in system performance. Why this level? Improvements in performance increases reliability on the system. ",
			keyword: "Reliability",
		  },
		  {
			metric: "Fee reduction",
			strength: "High",
			description:
			  " Measures: Reduction in fees generated by a contribution. Why this level? A reduction in fees improves the affordability to operate the OP Stack and could foster its adoption by other parties. ",
			keyword: "Gas Fees",
		  },
		  {
			metric: "Gas costs reduction in contract creation",
			strength: "High",
			description:
			  "Measures: Amount of gas reductions in contract creation generated by a contribution. Why this level? Making deployment of contracts more accessible enables more builders and increases the affordability of more complex interactions. ",
			keyword: "Gas Fees",
		  },
		  {
			metric: "Number of weekly Github packages downloaded",
			strength: "Medium",
			description:
			  "Measures: Number of weekly downloads. Why this level? There is no clear way to know if the people downloading the package are using it to build on Optimism, this may change though if the package is OP Stack specific. ",
			keyword: "Simplicity",
		  },
		  {
			metric: "Number of NPM weekly downloads",
			strength: "Medium",
			description:
			  "Measures: Number of weekly downloads. Why this level? There is no clear way to know if the people downloading the package are using it to build on Optimism, this may change though if the package is OP Stack specific. ",
			keyword: "Simplicity",
		  },

		  {
			metric: "Percentage of total OP Stack nodes supported",
			strength: "High",
			description:
			  "Measures: Percentage of nodes provided with support through this client. Why this level? An increase in client support enables redundancy of the support provided and increases resilience of the system. ",
			keyword: "Redundancy",
		  },
		  {
			metric: "Uptime",
			strength: "High",
			description:
			  "Measures: How reliable the provision of a service is. Why this level? Reliable service provision improves how dependable the Optimism ecosystem is for builders. ",
			keyword: "Stability",
		  },
		  {
			metric: "Number of dependent Github repositories",
			strength: "Medium",
			description:
			  "Measures: Number of dependencies from other repositories. Why this level? A repository which is not Optimism specific may include dependencies that are not benefiting the Optimism Ecosystem, making its impact appear greater than it is.  ",
			keyword: "Extensibility",
		  },
		  {
			metric:
			  "Number of positive testimonies from OP Stack core contributors",
			strength: "High",
			description:
			  "Measures: How useful core contributors have found a resource to be. Why this level? This metric clearly signals the perceived positive value of a contribution by OP specific beneficiaries.  ",
			keyword: "Utility",
		  },
		  {
			metric: "Number of dependencies from the OP Stack",
			strength: "High",
			description:
			  "Measures: Dependencies the OP Stack has on an external resource. Why this level? A larger number of dependencies could point to this resources being extremely valuable to the Ecosystem.  ",
			keyword: "Utility",
		  },
		  {
			metric: "Type of dependency from the OP Stack",
			strength: "High",
			description:
			  "Measures: Type of dependencies the OP Stack has on an external resource. Why this level? Some dependencies are fundamental to the OP Stack, while others could be less critical. However, for now recommendation is to value both highly. ",
			keyword: "       ",
		  },
		]}
	  />
	</>
  );
}

export function CollapsibleII({
  TableData,
}: {
  TableData: {
	metric: string;
	strength: string;
	description: string;
	keyword: string;
  }[];
}) {
  function getKeywordColor(keyword?: string) {
	if (!keyword) return "bg-gray-600 text-gray-100";

	const colorMap: { [key: string]: string } = {
	  awareness: "bg-violet-700 text-violet-100",
	  adaptability: "bg-indigo-700 text-indigo-100",
	  dependability: "bg-gray-700 text-gray-100",
	  familiarity: "bg-amber-700 text-emerald-100",
	  "gas fees": "bg-orange-700 text-orange-100",
	  reliability: "bg-blue-700 text-blue-100",
	  simplicity: "bg-purple-700 text-purple-100",
	  stability: "bg-pink-700 text-pink-100",
	  redundancy: "bg-cyan-700 text-green-100",
	  extensibility: "bg-orange-600 text-yellow-100",
	  utility: "bg-red-700 text-red-100",
	  modularity: "bg-slate-700 text-green-100",
	  understanding: "bg-teal-700 text-teal-100",
	};

	const key = keyword.toLowerCase();
	return colorMap[key] || "bg-blue-700 text-blue-100";
  }

  function getStrengthColor(strength?: string) {
	if (!strength) return "bg-gray-600 text-white";

	const colorMap: { [key: string]: string } = {
	  high: "bg-green-600 text-white",
	  medium: "bg-sky-700 text-slate-100",
	  low: "bg-red-600 text-white",
	};

	const key = strength.toLowerCase();
	return colorMap[key] || "bg-gray-600 text-white";
  }
  return (
	<>
	  <div className="flex flex-col px-4">
		<h1 className="text-2xl py-2 pt-8 font-black"> 📊 🌱 Metrics Garden</h1>
		<p>
		  Here you can find some metrics associated to the relevant terms
		  described above. These metrics are examples (there’s many more!) of
		  what can be used to measure the impact of a contribution. Always
		  consider how the metrics chosen by a project and how they are measured
		  signal the impact generated to the OP Stack.{" "}
		</p>
		<br />
		<p className="py-4">
		  Metrics have been graded as low-medium-high impact, based on how
		  useful a metric is at informing the impact of a contribution to the
		  Optimism Ecosystem.
		</p>
	  </div>
	  <table className="w-full text-left mt-2 border-separate border-spacing-y-1">
		<thead>
		  <tr className="text-zinc-400 text-sm">
			<th className="px-2">Metric name</th>
			<th className="px-2">Metric strength</th>
			<th className="px-2">What & Why</th>
			<th className="px-2">Keyword it relates to</th>
		  </tr>
		</thead>
		<tbody>
		  {TableData.map((row, idx) => (
			<tr key={idx} className="bg-zinc-800 text-sm rounded-md">
			  <td className="px-2 py-2 text-zinc-100">{row.metric}</td>
			  <td className="px-2 py-2">
				<span
				  className={`px-2 py-0.5 rounded-md text-xs font-medium ${getStrengthColor(
					row.strength
				  )}`}
				>
				  {row.strength ?? "—"}
				</span>
			  </td>
			  <td className="px-2 py-2 w-1/2 text-zinc-300">
				{row.description}
			  </td>
			  <td className="px-2 py-2">
				<span
				  className={`px-2 py-0.5 rounded-md text-xs font-medium ${getKeywordColor(
					row.keyword
				  )}`}
				>
				  {row.keyword ?? "—"}
				</span>
			  </td>
			</tr>
		  ))}
		</tbody>
	  </table>
	</>
  );
}
