export default function Definition() {
  return (
    <>
      <div className="flex flex-col  gap-1 py-2 px-4">
        <h1 className="text-2xl  py-2 font-black"> ⚖️ Collective Governance</h1>
        <h2 className="text-xl font-bold pb-2">
          Definition of impact within the category
        </h2>
        <p>
          Collective Governance is the process of decision-making among a group
          of individuals that will allow the Optimism Collective to achieve the
          Optimistic Vision.
          <br />
          Impact can be generated by creating conditions that enable all members
          participate in governance processes at various stages.
        </p>
        <span className="gap-2 py-3 px-1 rounded-md text-base font-medium text-zinc-300 bg-zinc-800 hover:text-white transition-colors">
          🔴 Of the top 1k delegates with the most voting power, 312 are
          considered
          <a
            href="https://optimism.curiahub.xyz/participation"
            className="text-white/50 underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            {" "}
            “active”{" "}
          </a>
          Let’s increase this number!
        </span>
      </div>
    </>
  );
}
