import Collapsible from "../op-stack/Collapsible";

export default function RelevantTerms() {
  return (
	<>
	      <h1 className="text-2xl py-2 pt-8 font-black">  Relevant terms to consider:</h1>
	  <Collapsible
		Title="Governance Accessibility"
		Definition="Governance accessibility enables a diversity of perspectives from various backgrounds to participate in decision-making processes, such as voting, by lowering barriers to entry."
		QuestionOne="Did this contribution led to an increase in the number of delegates? "
		QuestionTwo="How did this contribution increase the diversity of participants in the Collective Governance members?"
		Example="Through the creation of onboarding governance sessions in Swahili, the red sunny project increased the number of Delegates from East Africa."
		Keywords={["new delegates", "lower barriers to entry", "onboarding", "representation", "usability"]}
		TableData={[
		  {
			metric: "On-chain content engagement (NFT mints, attestations) with Governance Accessibility resources",
			strength: "Medium",
			description:
			  "Measures: On-chain engagement with content. Why this level? Some value is being generated so that people feel compelled to interact on-chain with it. The provision of on-chain data can contribute to identity development.",
			keyword: "Lower barriers to entry",
		  },
		  {
			metric: "Increase in number of delegates",
			strength: "Medium",
			description:
			  "Measures: Increase in number of delegates generated by an initiative. Why this level? While an increase in delegates is good, how good it is will increase based on their active engagement in the Collective.",
			keyword: "New delegates",
		  },
		]}
	  />
	  <Collapsible
		Title="Governance Participation"
		Definition="Governance participation is a collaborative process where members communicate and take part in governance activities."
		QuestionOne="How did this contribution support delegates or badgeholders to increase their participation in governance?"
		QuestionTwo="Did this contribution improve the collaboration between delegates or badgeholders?"
		Example="The distribution of summaries on proposals to be voted on, by project blue Sunny, has led to an increase in delegate voting turn out of XX%.  "
		Keywords={[
		  "collaboration",
		  "communication",
		  "voting",
		  "involvement",
		  "engagement",
		]}
		TableData={[
		  {
			metric: "Increase in delegate individual activeness in proposals",
			strength: "High",
			description:
			  "Measures: Increase in delegate participation on a proposal generated by a contribution. Why this level? Optimism’s Governance changes rapidly, improvements in communication that makes it easier for delegates to keep up and be involved in governance benefits the Collective. ",
			keyword: "Communication",
		  },
		  {
			metric: "Monthly active delegates/badgeholders using the platform",
			strength: "High",
			description:
			  "Measures: Number of delegates or badgeholders who have participated in governance through a platform. Why this level? Tooling for governance improves the experience and ease of participating in governance. ",
			keyword: "Engagement",
		  },
		]}
	  />
	  <Collapsible
		Title="Understandability"
		Definition="Understandability refers to the degree to which processes and responsibilities are easily interpreted by all members."
		QuestionOne="How many delegates leveraged this content to inform their participation? "
		QuestionTwo="Did this contribution provide enhanced visual communications that provide insights into the Collective Governance?"
		Example="The workshop, created by smol Sunny, helped 15 teams understand how to apply for RetroPGF.  "
		Keywords={["clarity", "comprehensibleness", "easy interpretation", "comunication"]}
		TableData={[
		  {
			metric: "Off-chain content Engagement (shares, likes clicks, etc)",
			strength: "Low",
			description:
			  "Measures: Engagement a piece of content has had. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric. ",
			keyword: "Understandability",
		  },
		  {
			metric: "Content impressions (views, reproductions)",
			strength: "Low",
			description:
			  "Measures: Number of impressions a piece of content has had. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric.",
			keyword: "Understandability",
		  },
		  {
			metric: "Positive testimonials from badgeholders/delegates",
			strength: "Medium",
			description:
			  "Measures: How satisfied badgeholder/delegates are with the  contribution in improving their ability to understand governance. Why this level? Verifying testimonials can be challenging, but it can provide insight into how useful a contribution has been.",
			keyword: "Understandability",
		  },
		  {
			metric: "Increase in number of delegations from minority holder wallets",
			strength: "Medium",
			description:
			  "Measures: Increase in minority wallets that have delegated their tokens after an initiative. Why this level? This metric clearly signals that more people understand how to delegate and increases the total votable supply. ",
			keyword: "Comprehensibleness",
		  },
		]}
	  />
	   <Collapsible
		Title="Accountability"
		Definition="A system with independent parts facilitates collaborative and extensible development. Independent teams can evolve and improve independent components, eliminating extensive coordination."
		QuestionOne="Is this contribution designed to coexist and support a modular environment? "
		QuestionTwo="Can this contribution be used as a building block of several other pieces? "
		Example="  "
		Keywords={["modules", "adaptability", "extensibility", "utility"]}
		TableData={[
		  {
			metric: "Number of dependent Github repositories",
			strength: "Medium",
			description:
			  "Measures: Number of dependencies from other repositories. Why this level? A repository which is not Optimism specific may include dependencies that are not benefiting the Optimism Ecosystem, making its impact appear greater than it is.  ",
			keyword: "Extensibility",
		  },
		  {
			metric: "Number of positive testimonies from OP Stack core contributors",
			strength: "High",
			description:
			  "Measures: How useful core contributors have found a resource to be. Why this level? This metric clearly signals the perceived positive value of a contribution by OP specific beneficiaries.  ",
			keyword: "Utility",
		  },
		  {
			metric: "Number of dependencies from the OP Stack",
			strength: "High",
			description:
			  "Measures: Dependencies the OP Stack has on an external resource. Why this level? A larger number of dependencies could point to this resources being extremely valuable to the Ecosystem.  ",
			keyword: "Utility",
		  },
		  {
			metric: "Type of dependency from the OP Stack",
			strength: "High",
			description:
			  "Measures: Type of dependencies the OP Stack has on an external resource. Why this level? Some dependencies are fundamental to the OP Stack, while others could be less critical. However, for now recommendation is to value both highly. ",
			keyword: "       ",
		  },
		]}
	  />
	   <Collapsible
		Title="Capture Resistance"
		Definition="Awareness of the OP Stack means understanding how its parts are arranged and work together. "
		QuestionOne="Did this project provide insight into how its components can be leveraged?  "
		QuestionTwo="Did this contribution led to more teams building with the OP Stack? "
		Example="By leveraging the tool created by blue sunny, two new teams spun out their own OP Chains. "
		Keywords={["familiarity", "understanding", "effective use", "adoption"]}
		TableData={[
		  {
			metric: "Content impressions",
			strength: "Low",
			description:
			  "Measures: Number of impressions this piece of content has had. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric. ",
			keyword: "Familiarity",
		  },
		  {
			metric: "Number of Github stars",
			strength: "Low",
			description:
			  "Measures: Number of stars a Github repo has received. Why this level? There is no clear way to know if starring a project can be equated to any value being derived from it. ",
			keyword: "Familiarity",
		  },
		  {
			metric: "Number of event attendees",
			strength: "Low",
			description:
			  "Measures: Number of people who attended an event. Why this level? Depending on the type and content in the event, its value to the Optimism Ecosystem may be low or high based on how fruitful it is to engage people with Optimism. ",
			keyword: "Understanding",
		  },
		  {
			metric: "Number of content material created on the OP Stack",
			strength: "Low",
			description:
			  "Measures: Content created on the OP Stack. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric.",
			keyword: "Familiarity",
		  },
		  {
			metric: "Level of engagement with OP Stack content",
			strength: "Low",
			description:
			  "Measures: Engagement a piece of content has had. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric.",
			keyword: "Understanding",
		  },
		]}
	  />
	</>
  );
}

