import Collapsible from "../op-stack/Collapsible";

export default function RelevantTerms() {
  return (
	<>
	      <h1 className="text-2xl py-2 pt-8 font-black px-4">  Relevant terms to consider:</h1>
	  <Collapsible
		Title="Governance Accessibility"
		Definition="Governance accessibility enables a diversity of perspectives from various backgrounds to participate in decision-making processes, such as voting, by lowering barriers to entry."
		QuestionOne="Did this contribution led to an increase in the number of delegates? "
		QuestionTwo="How did this contribution increase the diversity of participants in the Collective Governance members?"
		Example="Through the creation of onboarding governance sessions in Swahili, the red sunny project increased the number of Delegates from East Africa."
		Keywords={["new delegates", "lower barriers to entry", "onboarding", "representation", "usability"]}
		TableData={[
		  {
			metric: "On-chain content engagement (NFT mints, attestations) with Governance Accessibility resources",
			strength: "Medium",
			description:
			  "Measures: On-chain engagement with content. Why this level? Some value is being generated so that people feel compelled to interact on-chain with it. The provision of on-chain data can contribute to identity development.",
			keyword: "Lower barriers to entry",
		  },
		  {
			metric: "Increase in number of delegates",
			strength: "Medium",
			description:
			  "Measures: Increase in number of delegates generated by an initiative. Why this level? While an increase in delegates is good, how good it is will increase based on their active engagement in the Collective.",
			keyword: "New delegates",
		  },
		]}
	  />
	  <Collapsible
		Title="Governance Participation"
		Definition="Governance participation is a collaborative process where members communicate and take part in governance activities."
		QuestionOne="How did this contribution support delegates or badgeholders to increase their participation in governance?"
		QuestionTwo="Did this contribution improve the collaboration between delegates or badgeholders?"
		Example="The distribution of summaries on proposals to be voted on, by project blue Sunny, has led to an increase in delegate voting turn out of XX%.  "
		Keywords={[
		  "collaboration",
		  "communication",
		  "voting",
		  "involvement",
		  "engagement",
		]}
		TableData={[
		  {
			metric: "Increase in delegate individual activeness in proposals",
			strength: "High",
			description:
			  "Measures: Increase in delegate participation on a proposal generated by a contribution. Why this level? Optimism’s Governance changes rapidly, improvements in communication that makes it easier for delegates to keep up and be involved in governance benefits the Collective. ",
			keyword: "Communication",
		  },
		  {
			metric: "Monthly active delegates/badgeholders using the platform",
			strength: "High",
			description:
			  "Measures: Number of delegates or badgeholders who have participated in governance through a platform. Why this level? Tooling for governance improves the experience and ease of participating in governance. ",
			keyword: "Engagement",
		  },
		]}
	  />
	  <Collapsible
		Title="Understandability"
		Definition="Understandability refers to the degree to which processes and responsibilities are easily interpreted by all members."
		QuestionOne="How many delegates leveraged this content to inform their participation? "
		QuestionTwo="Did this contribution provide enhanced visual communications that provide insights into the Collective Governance?"
		Example="The workshop, created by smol Sunny, helped 15 teams understand how to apply for RetroPGF.  "
		Keywords={["clarity", "comprehensibleness", "easy interpretation", "comunication"]}
		TableData={[
		  {
			metric: "Off-chain content Engagement (shares, likes clicks, etc)",
			strength: "Low",
			description:
			  "Measures: Engagement a piece of content has had. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric. ",
			keyword: "Understandability",
		  },
		  {
			metric: "Content impressions (views, reproductions)",
			strength: "Low",
			description:
			  "Measures: Number of impressions a piece of content has had. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric.",
			keyword: "Understandability",
		  },
		  {
			metric: "Positive testimonials from badgeholders/delegates",
			strength: "Medium",
			description:
			  "Measures: How satisfied badgeholder/delegates are with the  contribution in improving their ability to understand governance. Why this level? Verifying testimonials can be challenging, but it can provide insight into how useful a contribution has been.",
			keyword: "Understandability",
		  },
		  {
			metric: "Increase in number of delegations from minority holder wallets",
			strength: "Medium",
			description:
			  "Measures: Increase in minority wallets that have delegated their tokens after an initiative. Why this level? This metric clearly signals that more people understand how to delegate and increases the total votable supply. ",
			keyword: "Comprehensibleness",
		  },
		]}
	  />
	   <Collapsible
		Title="Accountability"
		Definition="Accountability refers to the obligation of both voters and grantees to conduct actions and decisions transparently."
		QuestionOne="Did this contribution increase the ability for members of the Grant Council to make decisions on funding allocation based on grantees previous performance?  "
		QuestionTwo="Did this contribution increase the accessibility to data that can be leveraged for accountability?  "
		Example="  "
		Keywords={["transparency", "visibility", "accesibility of data", "monitoring", "compilance", "oversight"]}
		TableData={[
		  {
			metric: "Increase in number of delegates voting in a proposal",
			strength: "high",
			description:
			  "Measures: Number of delegates that voted in a proposal as a result of a contribution. Why this level? Participation in the decision-making of the collective is fundamental and information on this participation increases the ability to hold delegates accountable.   ",
			keyword: "monitoring",
		  },
		  {
			metric: "Attestations received by the RetroPGF applicant",
			strength: "High",
			description:
			  "Measures: Public signaling by users on the impact of a contribution through attestations.  Why this level? The use of attestations increases data availability for Optimism’s Citizenship.",
			keyword: "accesibility of data",
		  },
		  {
			metric: "Increase in number of delegates explaining their voting rationale",
			strength: "High",
			description:
			  "Measures: Number of delegates that have shared their voting rationale derived from a contribution. Why this level?  An increase in information that is shared by delegates enables their token holders to hold them accountable for their participation. ",
			keyword: "transparency",
		  },
		  {
			metric: "Number of grants executed as specified",
			strength: "High",
			description:
			  "Measures: Number of grants an applicant has completed according to the requirements. Why this level? By completing their grants according to the requirements Grantees increase the trust Token holders have in the Optimism Governance. ",
			keyword: "monitoring",
		  },
		]}
	  />
	   <Collapsible
		Title="Capture Resistance"
		Definition="Capture Resistance refers to the ability of the governance of the Optimism Collective to resist being captured by one or multiple actors."
		QuestionOne="Did this contribution support a broader distribution of voting power among delegates?  "
		QuestionTwo="Did this contribution result in an increase in the votable supply of OP tokens? "
		Example="The video, created by Green Sunny, helped XX token holders understand how to delegate their voting power to minority delegates. "
		Keywords={["concentration of voting power", "resilience", "votable supply", "delegation of tokens"]}
		TableData={[
		  {
			metric: "Changes in voting power distribution held within the top 10 delegates",
			strength: "Medium",
			description:
			  "Measures: Changes in voting power distribution generated by a contribution. Why this level?",
			keyword: "concentration of voting power",
		  },
		  {
			metric: "Increase in votable supply",
			strength: "high",
			description:
			  "Measures: Increase in delegated tokens. Why this level? An increase in votable supply translates to more participants in governance (through delegation).",
			keyword: "capture resistance",
		  }, 
		]}
	  />
	</>
  );
}

