export default function Definition() {
  return (
    <>
      <div className="flex flex-col  gap-1 py-2">
        <h1 className="text-2xl  py-2 font-black">
          💃🏽 End User Experience and Adoption{" "}
        </h1>
        <h2 className="text-xl font-bold pb-2">
          Definition of impact within the category{" "}
        </h2>
        <p>
          End User Experience refers to the interactions consumers of the
          Optimism Collective have wth OP Chain powered products. Adoption
          refers to the process by which consumers integrate a product or
          technology to their daily routines or lives. <br />
          Impact within this category is generated by contributions that enable
          a seamless user experience and foster the long-term engagement of
          consumers.{" "}
        </p>
        <span className="flex items-center gap-2 py-3 px-1 rounded-md text-base font-medium text-zinc-300 bg-zinc-800 hover:text-white transition-colors">
          🔴 OP Mainnet’s most used project had
          <a
            href="https://dune.com/optimismfnd/Optimism"
            className="text-white/50 underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            10k addresses{" "}
          </a>
          interacting with it daily during September 2023.
        </span>
      </div>
    </>
  );
}
