import Collapsible from "../op-stack/Collapsible";

export default function RelevantTerms() {
  return (
	<>
	  <h1 className="text-2xl py-2 pt-8 font-black px-4"> Relevant terms:</h1>
	  <Collapsible
		Title="Awareness"
		Definition="Awareness refers to the initial knowledge individuals acquire about a new product on an OP Chain."
		QuestionOne="Did this contribution increase public awareness of existing products in the Optimism Collective?"
		QuestionTwo="How many users first learned of X product built on an OP Chain through this contribution?"
		Example="The podcast on Ethers Phoenix created by smol sunny was the first NFT 100 users minted on Zora."
		Keywords={["awareness", "visibility", "interest", "clarity"]}
		TableData={[
		  {
			metric: "Number of impressions",
			strength: "Low",
			description:
			  "Measures: Number of impressions a content received. Why this level? The number of impressions can hardly inform what impact or benefit those exposed to the content derived. ",
			keyword: "interest",
		  },
		  {
			metric: "Content open rate",
			strength: "Low",
			description:
			  "Measures: Number of addresses that have opened the email containing content generated by an initiative.  Why this level? This metric does not provide insight into how the receivers engage with the content or the benefit derived from it. ",
			keyword: "visibility",
		  },
		  {
			metric: "Number of event attendees",
			strength: "Low",
			description:
			  "Measures: Number of people who attended an educational event organized by a project. Why this level? The level of this metric will variate depending on the theme of the event and the form through which attendance is proved.  ",
			keyword: "awareness",
		  },
		  {
			metric: "Number of users onboarded to the Optimism Collective",
			strength: "high",
			description:
			  "Measures: Number of new users onboarded through this contribution. Why this level? Given the right tools to prove it, an increase in users in Optimism benefits multiple members of the Ecosystem.  ",
			keyword: "awareness",
		  },
		  {
			metric: "Percentage growth of interactions",
			strength: "high",
			description:
			  "Measures: Increase in interactions with a project derived from a contribution. Why this level? This metric clearly signals that the contribution was effective in enabling users to engage.  ",
			keyword: "interest",
		  },
		  {
			metric: "Increase in number of cross OP Chain users",
			strength: "high",
			description:
			  "Measures: Increase in cross-chain interactions made by individual users.  Why this level? This metric can demonstrate a comprehensive exposure of users to the entirety of the Optimism ecosystem, benefitting the growth of projects in the Superchain.",
			keyword: "awareness",
		  },
		]}
	  />
	  <Collapsible
		Title="Discovery journey"
		Definition="Discovery journey refers to the dynamic and evolving process through which consumers explore, and ultimately embrace a new product."
		QuestionOne="Did this contribution led to more consumers exploring a specific product in an OP Chain?"
		QuestionTwo="Did this contribution improve the intuitiveness to interact with a product deployed on an OP Chain?"
		Example="A website that curated a set of the 10 most exciting projects in Optimism increased the number of people trying them by 15% percent the month after it went live.  "
		Keywords={[
		  "intuitiveness",
		  "exploration",
		  "novelty",
		  "identification of value",
		]}
		TableData={[
		  {
			metric: "Number of new wallets funded in an OP Chain",
			strength: "Low",
			description:
			  "Measures: Number of new addresses that have been funded as a result of a contribution.  Why this level? This metric provides some insight into the potential for these wallets to become active in the ecosystem, however, it does not signal actual interactions with Optimism. ",
			keyword: "exploration",
		  },
		  {
			metric: "Number of subscribers",
			strength: "Low",
			description:
			  "Measures: Number of addresses that receive the content generated by an initiative.  Why this level? This metric does not provide insight into how the receivers engage with the content or the benefit derived from it.  ",
			keyword: "novelty",
		  },
		  {
			metric: "Increase in number of interactions completed in Optimism",
			strength: "High",
			description:
			  "Measures: Increase in wallet interactions generated by a contribution. Why this level? This metric clearly signals growth in the adoption of Optimism.   ",
			keyword: "intuitiveness",
		  },
		]}
	  />
	  <Collapsible
		Title="User Experience"
		Definition="Is how a user experiences and interacts with a product."
		QuestionOne="Did this contribution improve the bridging experience for new users of an OP Chain? "
		QuestionTwo="Did this contribution generated clear expectations for end users interacting with an OP Chain or product?  "
		Example="The bridging experience offered by blue sunny enabled 1K new users to bridge funds to an OP Chain for the first time. "
		Keywords={[
		  "usability",
		  "simplicity",
		  "accessibility",
		  "reliability",
		  "support",
		  "barriers",
		]}
		TableData={[
		  {
			metric: "Improvements in the user experience",
			strength: "Medium",
			description:
			  "Measures: Level of simplicity for transacting users Why this level? This metric signals an improvement  for users in their interactions in the Optimism Ecosystem.",
			keyword: "Barriers",
		  },
		  {
			metric: "Number of customer support queries resolved",
			strength: "Medium",
			description:
			  "Measures: Number of questions resolved by a team to enable end users in their journey. Why this level? Resolving questions that are specific to the Optimism Ecosystem enable a smooth interaction with different projects and can drive user growth. ",
			keyword: "Support",
		  },
		]}
	  />
	  <Collapsible
		Title="Adoption"
		Definition="Consumer adoption is the process by which individuals integrate a new product or technology into their lives."
		QuestionOne="Did this initiative lead to the growth of Monthly Active Users of a project in the OP Chains? "
		QuestionTwo="Did this initiative reduce the cost of new use cases in the OP Chains?"
		Example="The game created by anon sunny led to 20K new monthly active users on OP Mainnet."
		Keywords={["long-term engagement", "Perceived-value"]}
		TableData={[
		  {
			metric: "Increase in wallet interactions MoM per OP Chain",
			strength: "High",
			description:
			  "Measures: Increase in wallet interactions MoM generated by a contribution. Why this level? This metric clearly signals improved adoption and sustained engagement with Optimism.  ",
			keyword: "long-term engagement",
		  },
		  {
			metric:
			  "Increase in average number of addresses retained after first use",
			strength: "High",
			description:
			  "Measures: Increase in wallet retention over time. Why this level? This metric clearly signals improved engagement with Optimism. ",
			keyword: "Perceived-value",
		  },
		  {
			metric:
			  "Number of returning unique transacting addresses per project",
			strength: "High",
			description:
			  "Measures: The engagement of users with a contribution after it’s deployment. Why this level? This metric clearly signals sustained engagement with Optimism.  ",
			keyword: "long-term engagement",
		  },
		  {
			metric: "Percentage growth in transactions per day",
			strength: "High",
			description:
			  "Measures: Transactions driven by a project. Why this level? An increase in the percentage of fees generated by a project can speak to the adoption it has had among users vs other projects in that chain and it’s value to the ecosystem. ",
			keyword: "long-term engagement",
		  },
		  {
			metric: "Growth in number of monthly active addresses",
			strength: "High",
			description:
			  "Measures: Increase in monthly active users Why this level? An increase monthly active users hints to a project gaining traction among the community in a sustained way, benefitting the Collective in the long-run. ",
			keyword: "long-term engagement",
		  },
		  {
			metric: "Daily active users",
			strength: "High",
			description:
			  "Measures: Daily transactions driven by a project.  Why this level? An increase in daily active users increases the fees generated to the Optimism Ecosystem and can speak to the utility of a project for its users.  ",
			keyword: "long-term engagement",
		  },
		]}
	  />
	  <Collapsible
		Title="Education"
		Definition="Education refers to the process of equipping consumers with the knowledge and skills necessary to effectively use a product. "
		QuestionOne="Did this contribution enhance the on-ramping of funds into the OP Chains?"
		QuestionTwo="How does the quality of the content generated by this initiative compare to similar initiatives?   "
		Example="The creation of an SDK to include credit card payments for OP Chain wallets enabled 5K new monthly transactions.  "
		Keywords={[
		  "practical",
		  "audience",
		  "content",
		  "quality",
		  "engagement",
		]}
		TableData={[
		  {
			metric: "Number of views",
			strength: "Low",
			description:
			  "Measures: Number of times a piece of content has been viewed. Why this level? The direct benefit derived from people viewing a piece of content is very difficult to assess. It is also unclear if those who viewed it actually benefit from the content.  ",
			keyword: "content",
		  },
		  {
			metric: "Increase in total value bridged into Optimism",
			strength: "High",
			description:
			  "Measures: Increase in value bridged into Optimism following a contribution attributable to that contribution.  Why this level? Handholding new users through the bridging process enables numerous subsequent interactions in the ecosystem, the completion of bridging must be attributable to the project.",
			keyword: "engagement",
		  },
		  {
			metric: "Increase in number of addresses transacting for the first time with Optimism",
			strength: "High",
			description:
			  "Measures: The number of addresses a project has onboarded into Optimism. Why this level? This metric clearly shows the increase in users in the Optimism Ecosystem generated by this project. ",
			keyword: "engagement",
		  },
		]}
	  />
	</>
  );
}
