import Collapsible from "./Collapsible";

export default function RelevantTerms() {
  return (
    <>
      <Collapsible
        Title="Performance"
        Definition="Performance is about ensuring a network runs smoothly, ensuring all transactions and smart contracts are executed without issues while keeping costs low."
        QuestionOne="Did the contribution enable a reduction on time to load for applications or nodes being set up?"
        QuestionTwo="Did the contribution enable an increase in how efficiently resources are used?"
        Example="The research Alice created on gas optimization in optimistic rollups enabled the transactions in Bedrock to be x times cheaper than before."
        Keywords={["stability", "gas fees", "reliability", "monitoring"]}
        TableData={[
          {
            metric: "Runtime gas costs reduction",
            strength: "High",
            description:
              "Measures: Reduction in runtime generated by a contribution. Why this level? Increase in the efficiency and performance of the OP Stack makes its operation more affordable.",
            keyword: "Gas Fees",
          },
          {
            metric: "Response time for RPC calls",
            strength: "High",
            description:
              "Measures:Time to get a response to an RPC call. Why this level? A low response time to RPC calls makes developing and operating in the Optimism Ecosystem reliable.",
            keyword: "Reliability",
          },
          {
            metric: "Total OP Chains RPC served",
            strength: "High",
            description:
              " Measures: Dependencies on OP Chains on a particular RPC. Why this level? An increase in the provision of service to OP Chains enables the creation of redundancy in case of malfunctions. ",
            keyword: "Reliability",
          },
          {
            metric: "Performance Improvement",
            strength: "High",
            description:
              " Measures: Improvement in system performance. Why this level? Improvements in performance increases reliability on the system. ",
            keyword: "Reliability",
          },
          {
            metric: "Fee reduction",
            strength: "High",
            description:
              " Measures: Reduction in fees generated by a contribution. Why this level? A reduction in fees improves the affordability to operate the OP Stack and could foster its adoption by other parties. ",
            keyword: "Gas Fees",
          },
          {
            metric: "Gas costs reduction in contract creation",
            strength: "High",
            description:
              "Measures: Amount of gas reductions in contract creation generated by a contribution. Why this level? Making deployment of contracts more accessible enables more builders and increases the affordability of more complex interactions. ",
            keyword: "Gas Fees",
          },
        ]}
      />
      <Collapsible
        Title="Security"
        Definition="Security involves reducing surface area for attacks and finding, reporting, and or fixing bugs."
        QuestionOne="Does this contribution support the simplification of the OP Stack code?"
        QuestionTwo="Did this contribution reduced the number of bugs in the OP Stack?"
        Example="The use of red sunny tool enabled the simulation of attacks to the OP Stack so as to discover vulnerabilities in the code. "
        Keywords={[
          "vulnerabilities",
          "audits",
          "bugs",
          "code reduction",
          "simplicity",
        ]}
        TableData={[
          {
            metric: "Number of weekly Github packages downloaded",
            strength: "Medium",
            description:
              "Measures: Number of weekly downloads. Why this level? There is no clear way to know if the people downloading the package are using it to build on Optimism, this may change though if the package is OP Stack specific. ",
            keyword: "Simplicity",
          },
          {
            metric: "Number of NPM weekly downloads",
            strength: "Medium",
            description:
              "Measures: Number of weekly downloads. Why this level? There is no clear way to know if the people downloading the package are using it to build on Optimism, this may change though if the package is OP Stack specific. ",
            keyword: "Simplicity",
          },
        ]}
      />
      <Collapsible
        Title="Resilience"
        Definition="Resilience encompasses the ability to ensure the system remains robust and dependable, to grow and manage increased use and to swiftly restore operations following a disruption."
        QuestionOne="Does this contribution enable the operational continuity of the OP Chains in the case of a system failure on one of the OP Stack components?"
        QuestionTwo="Does this contribution support the efficient management of increases in demand?"
        Example="The contribution by red sunny project enabled the spinning of ## new nodes. "
        Keywords={["robust", "dependable", "redundancy", "recovery"]}
        TableData={[
          {
            metric: "Percentage of total OP Stack nodes supported",
            strength: "High",
            description:
              "Measures: Percentage of nodes provided with support through this client. Why this level? An increase in client support enables redundancy of the support provided and increases resilience of the system. ",
            keyword: "Redundancy",
          },
          {
            metric: "Uptime",
            strength: "High",
            description:
              "Measures: How reliable the provision of a service is. Why this level? Reliable service provision improves how dependable the Optimism ecosystem is for builders. ",
            keyword: "Stability",
          },
        ]}
      />
	   <Collapsible
        Title="Modularity"
        Definition="A system with independent parts facilitates collaborative and extensible development. Independent teams can evolve and improve independent components, eliminating extensive coordination."
        QuestionOne="Is this contribution designed to coexist and support a modular environment? "
        QuestionTwo="Can this contribution be used as a building block of several other pieces? "
        Example="  "
        Keywords={["modules", "adaptability", "extensibility", "utility"]}
        TableData={[
          {
            metric: "Number of dependent Github repositories",
            strength: "Medium",
            description:
              "Measures: Number of dependencies from other repositories. Why this level? A repository which is not Optimism specific may include dependencies that are not benefiting the Optimism Ecosystem, making its impact appear greater than it is.  ",
            keyword: "Extensibility",
          },
          {
            metric: "Number of positive testimonies from OP Stack core contributors",
            strength: "High",
            description:
              "Measures: How useful core contributors have found a resource to be. Why this level? This metric clearly signals the perceived positive value of a contribution by OP specific beneficiaries.  ",
            keyword: "Utility",
          },
		  {
            metric: "Number of dependencies from the OP Stack",
            strength: "High",
            description:
              "Measures: Dependencies the OP Stack has on an external resource. Why this level? A larger number of dependencies could point to this resources being extremely valuable to the Ecosystem.  ",
            keyword: "Utility",
          },
		  {
            metric: "Type of dependency from the OP Stack",
            strength: "High",
            description:
              "Measures: Type of dependencies the OP Stack has on an external resource. Why this level? Some dependencies are fundamental to the OP Stack, while others could be less critical. However, for now recommendation is to value both highly. ",
            keyword: "       ",
          },
        ]}
      />
	   <Collapsible
        Title="Awareness"
        Definition="Awareness of the OP Stack means understanding how its parts are arranged and work together. "
        QuestionOne="Did this project provide insight into how its components can be leveraged?  "
        QuestionTwo="Did this contribution led to more teams building with the OP Stack? "
        Example="By leveraging the tool created by blue sunny, two new teams spun out their own OP Chains. "
        Keywords={["familiarity", "understanding", "effective use", "adoption"]}
        TableData={[
          {
            metric: "Content impressions",
            strength: "Low",
            description:
              "Measures: Number of impressions this piece of content has had. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric. ",
            keyword: "Familiarity",
          },
          {
            metric: "Number of Github stars",
            strength: "Low",
            description:
              "Measures: Number of stars a Github repo has received. Why this level? There is no clear way to know if starring a project can be equated to any value being derived from it. ",
            keyword: "Familiarity",
          },
		  {
            metric: "Number of event attendees",
            strength: "Low",
            description:
              "Measures: Number of people who attended an event. Why this level? Depending on the type and content in the event, its value to the Optimism Ecosystem may be low or high based on how fruitful it is to engage people with Optimism. ",
            keyword: "Understanding",
          },
		  {
            metric: "Number of content material created on the OP Stack",
            strength: "Low",
            description:
              "Measures: Content created on the OP Stack. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric.",
            keyword: "Familiarity",
          },
		  {
            metric: "Level of engagement with OP Stack content",
            strength: "Low",
            description:
              "Measures: Engagement a piece of content has had. Why this level? There is no clear way to know how much value was derived by the Collective based on this metric.",
            keyword: "Understanding",
          },
        ]}
      />
    </>
  );
}

